FROM python:3.13
WORKDIR /app
COPY /llm/requirements.txt /app
RUN pip install --upgrade pip

#安裝 Rust for tiktoken
RUN curl https://sh.rustup.rs -sSf | sh -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"

RUN apt-get update && \
    apt-get install -y \
    telnet \
    vim \
    build-essential \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir -r requirements.txt
COPY /llm .
CMD ["python", "main.py"]
